CREATE TABLE `SL_CARD` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `rarity` varchar(255) NOT NULL,
  `ownerId` int(11) NOT NULL,
  `published` tinyint(4) NOT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=latin1;

INSERT INTO `SL_CARD` (`id`,`name`,`rarity`,`image`,`ownerId`,`published`,`type`) VALUES 
(1,"Netherlands","normal","Massachusetts",2,"1","limited"),
(2,"Switzerland","normal","PV",6,"0","limited"),
(3,"Congo, the Democratic Republic of the","normal","Antioquia",8,"0","common"),
(4,"Ukraine","epic","Western Australia",1,"0","limited"),
(5,"United Kingdom (Great Britain)","normal","JI",2,"0","common"),
(6,"Tanzania","normal","NE",6,"1","limited"),
(7,"Djibouti","normal","Lagos",2,"0","limited"),
(8,"Antigua and Barbuda","normal","Minas Gerais",1,"0","common"),
(9,"Korea, North","legendary","La Libertad",7,"1","limited"),
(10,"Burundi","normal","NO",3,"1","limited"),
(11,"Togo","normal","Kent",6,"1","common"),
(12,"Myanmar","epic","WI",6,"0","common"),
(13,"Moldova","normal","SI",8,"0","common"),
(14,"Mauritania","legendary","SI",3,"1","common"),
(15,"Aruba","normal","Sląskie",6,"1","common"),
(16,"Albania","epic","O",2,"1","common"),
(17,"Fiji","normal","MI",8,"0","common"),
(18,"Pitcairn Islands","legendary","Istanbul",1,"0","limited"),
(19,"Tokelau","epic","C",3,"1","common"),
(20,"Hungary","legendary","Jalisco",7,"0","common"),
(21,"Niue","epic","UP",2,"0","limited"),
(22,"Tajikistan","epic","Mississippi",6,"1","common"),
(23,"Macao","normal","ERM",5,"1","limited"),
(24,"Saint Helena, Ascension and Tristan da Cunha","epic","HR",2,"1","common"),
(25,"Sierra Leone","normal","East Java",1,"0","limited"),
(26,"Mongolia","epic","Antwerpen",6,"0","limited"),
(27,"Andorra","epic","BEL",6,"1","limited"),
(28,"French Polynesia","epic","ANT",1,"0","limited"),
(29,"Uganda","normal","Leinster",2,"0","common"),
(30,"Albania","legendary","Rivers",5,"0","limited"),
(31,"Ireland","epic","Friesland",1,"1","common"),
(32,"Botswana","epic","Valparaíso",6,"0","limited"),
(33,"Tajikistan","legendary","Kurgan Oblast",4,"1","common"),
(34,"Northern Mariana Islands","epic","Puglia",3,"0","limited"),
(35,"Myanmar","epic","British Columbia",5,"1","limited"),
(36,"Lebanon","epic","H",4,"1","common"),
(37,"Laos","normal","Ist",5,"0","limited"),
(38,"Kuwait","epic","South Australia",4,"0","common"),
(39,"Liberia","epic","FL",6,"1","limited"),
(40,"Mauritius","legendary","QC",6,"0","common"),
(41,"Cambodia","normal","Radnorshire",8,"0","common"),
(42,"Saint Helena, Ascension and Tristan da Cunha","epic","I",1,"0","common"),
(43,"Lithuania","normal","PU",5,"1","limited"),
(44,"Trinidad and Tobago","legendary","Lombardia",2,"0","common"),
(45,"Nicaragua","normal","C",3,"0","limited"),
(46,"Myanmar","legendary","Gyeonggi",2,"0","limited"),
(47,"United Arab Emirates","epic","Antwerpen",1,"0","common"),
(48,"Switzerland","legendary","NI",3,"1","common"),
(49,"Saint Barthélemy","legendary","NI",8,"0","common"),
(50,"American Samoa","normal","PUN",5,"1","limited"),
(51,"Austria","epic","Guanacaste",8,"1","limited"),
(52,"Russian Federation","epic","QC",1,"0","common"),
(53,"Latvia","legendary","OÖ.",4,"1","common"),
(54,"Madagascar","epic","SJ",5,"1","common"),
(55,"Congo (Brazzaville)","normal","Limón",5,"1","limited"),
(56,"Lebanon","normal","HH",7,"1","common"),
(57,"Monaco","normal","San José",5,"0","limited"),
(58,"Guatemala","legendary","PIU",7,"0","common"),
(59,"Korea, North","legendary","Haute-Normandie",8,"0","limited"),
(60,"Jamaica","legendary","RM",4,"1","common"),
(61,"Lesotho","epic","AN",4,"1","limited"),
(62,"Liberia","normal","L.",4,"0","limited"),
(63,"Moldova","legendary","North Jeolla",5,"0","common"),
(64,"Congo (Brazzaville)","normal","OR",2,"0","limited"),
(65,"Mexico","legendary","Ontario",3,"1","limited"),
(66,"Anguilla","epic","NA",6,"1","common"),
(67,"Kiribati","epic","Rio de Janeiro",6,"1","limited"),
(68,"Costa Rica","normal","North Island",6,"1","common"),
(69,"Mauritius","normal","QC",8,"0","common"),
(70,"Luxembourg","normal","Poitou-Charentes",4,"1","limited"),
(71,"Anguilla","normal","GJ",7,"0","limited"),
(72,"Algeria","normal","East Java",7,"1","limited"),
(73,"Australia","epic","RJ",5,"1","common"),
(74,"Lesotho","legendary","Montana",6,"1","limited"),
(75,"Papua New Guinea","legendary","AN",6,"1","limited"),
(76,"Cape Verde","legendary","Newfoundland and Labrador",5,"1","limited"),
(77,"Nigeria","legendary","Bolívar",4,"1","limited"),
(78,"Tunisia","normal","Puebla",3,"0","limited"),
(79,"South Africa","epic","Piemonte",3,"0","common"),
(80,"Åland Islands","normal","JT",8,"0","common"),
(81,"Mauritius","legendary","TAS",7,"0","common"),
(82,"Somalia","legendary","Principado de Asturias",5,"0","limited"),
(83,"Laos","legendary","Małopolskie",5,"0","common"),
(84,"Turkmenistan","legendary","Vienna",8,"0","limited"),
(85,"Czech Republic","normal","JI",6,"1","common"),
(86,"Russian Federation","normal","DU",1,"0","limited"),
(87,"Jordan","legendary","OH",2,"1","limited"),
(88,"Turks and Caicos Islands","normal","Connacht",6,"1","limited"),
(89,"Sao Tome and Principe","legendary","CA",4,"1","limited"),
(90,"Belarus","normal","Alajuela",7,"1","common"),
(91,"Guinea","epic","Ist",8,"0","limited"),
(92,"Togo","epic","Sachsen",5,"0","common"),
(93,"Dominican Republic","epic","Mer",6,"1","limited"),
(94,"Christmas Island","normal","Dalarnas län",3,"1","common"),
(95,"Burundi","normal","East Java",3,"0","common"),
(96,"Cyprus","legendary","E",2,"1","limited"),
(97,"India","legendary","CDM",1,"1","common"),
(98,"Falkland Islands","epic","FA",1,"0","limited"),
(99,"Tokelau","normal","OK",5,"1","common"),
(100,"Albania","normal","RM",5,"1","limited");