version: '3.3'
networks:
  stream_network:

volumes:
  stream-mysql-volume:
  stream-rabbitmq-volume:

services:
  mysql:
    image: mysql:5
    container_name: stream-mysql
    ports:
      - 3306:3306
    env_file:
      - .env.prod
    volumes:
      - stream-mysql-volume:/var/lib/mysql
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
    networks:
      - stream_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  user:
    build: ./user-server/.
    container_name: stream-user-server
    ports: 
      - 9321:9321
    env_file:
      - .env.prod
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - stream_network

  card:
    build: ./card-server/.
    container_name: stream-card-server
    ports: 
      - 9322:9322
    env_file:
      - .env.prod
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - stream_network

  owner-statistics:
    build: ./owner-statistics-server/.
    container_name: stream-owner-statistics-server
    ports: 
      - 9323:9323
    env_file:
      - .env.prod
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - stream_network

  user-statistics:
    build: ./user-statistics-server/.
    container_name: stream-user-statistics-server
    ports: 
      - 9324:9324
    env_file:
      - .env.prod
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - stream_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: stream-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - stream-rabbitmq-volume:/var/lib/rabbitmq/
      - stream-rabbitmq-volume:/var/log/rabbitmq/
    env_file:
      - .env.prod
    networks:
      - stream_network
