# Test Request
GET http://localhost:9323/owner-statistics HTTP/1.1
Content-Type: application/json

###

POST http://localhost:9323/owner-statistics HTTP/1.1
Content-Type: application/json

{
    "id": 654,
    "ownerId": 654,
    "cardId": 654,
    "cardName": "OWNER TEST",
    "cardImage": "OWNER IMAGE",
    "cardRarity": "OWNER RARITY",
    "cardUses": 25
}

###

PUT http://localhost:9323/owner-statistics HTTP/1.1
Content-Type: application/json

{
    "id": 654,
    "ownerId": 654,
    "cardId": 654,
    "cardName": "UPDATED OWNER TEST",
    "cardImage": "OWNER IMAGE",
    "cardRarity": "OWNER RARITY",
    "cardUses": 35
}

###

DELETE http://localhost:9323/owner-statistics?id=654 HTTP/1.1
Content-Type: application/json

{
    "id": 654,
    "ownerId": 654,
    "cardId": 654,
    "cardName": "UPDATED OWNER TEST",
    "cardImage": "OWNER IMAGE",
    "cardRarity": "OWNER RARITY",
    "cardUses": 35
}