version: '3.3'
networks:
  stream_network:

volumes:
  stream-mysql-volume:
  stream-rabbitmq-volume:

services:
  mysql:
    image: mysql:5
    container_name: stream-mysql
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - .env.prod
    volumes:
      - stream-mysql-volume:/var/lib/mysql
      - ./user-migration.sql:/docker-entrypoint-initdb.d/user-migration.sql
    networks:
      - stream_network
  user:
    build: ./card-server/.
    container_name: stream-user-server
    ports: 
      - 9321:9321
    env_file:
      - .env.prod
    depends_on:
      - mysql
    networks:
      - stream_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: stream-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - stream-rabbitmq-volume:/var/lib/rabbitmq/
      - stream-rabbitmq-volume:/var/log/rabbitmq/
    env_file:
      - .env.prod
    networks:
      - stream_network
